spring:
  datasource:
    url: "jdbc:h2:file:/tmp/ffshow"
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: true

omdb:
  base-url: "https://www.omdbapi.com/"

security:
  apiKey: 959e1bfa8382c9e9a0f6ed343115adbd